# -*- coding: utf-8 -*-
"""Binning and Binarization | Discretization | Quantile Binning | KMeans Binningpynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhvGJtm6u0vRemGjY07pcbIcnQVjN3qZ
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = sns.load_dataset("titanic")
df.head()

df = df[['age', 'fare', 'survived']]

df.head()

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import cross_val_score
from sklearn.compose import ColumnTransformer

df.dropna(inplace=True)
df.isnull().sum()

df.head()

X = df.iloc[:,0:2]
Y = df.iloc[:,-1]

X.head()

Y.head()

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=42)

clf = DecisionTreeClassifier()
clf.fit(X_train,Y_train)

y_pred = clf.predict(X_test)

accuracy_score(Y_test,y_pred)

np.mean(cross_val_score(DecisionTreeClassifier(),X,Y,cv=5,scoring="accuracy"))

kb_age = KBinsDiscretizer(n_bins=15,encode="ordinal",strategy="quantile")
kb_fire = KBinsDiscretizer(n_bins=10,encode="ordinal",strategy="quantile")

trf = ColumnTransformer(
    [
        ("first",kb_age,[0]),
        ("second",kb_fire,[1])
    ]
)

X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.fit_transform(X_test)

trf.named_transformers_["first"].n_bins_

trf.named_transformers_["second"].n_bins_

trf.named_transformers_["first"].bin_edges_

trf.named_transformers_["second"].bin_edges_

df1 = pd.DataFrame({
    "age" : X_train["age"],
    "age_trf" : X_train_trf[:,0],
    "fare"   : X_train["fare"],
    "fare_trf" : X_train_trf[:,1]
})

df1.head()

df1["age_label"] = pd.cut(x=X_train["age"],bins=trf.named_transformers_["first"].bin_edges_[0].tolist())
df1["fare_label"] = pd.cut(x=X_train["fare"],bins=trf.named_transformers_["second"].bin_edges_[0].tolist())

df1.head()

clf = DecisionTreeClassifier()
clf.fit(X_train_trf,Y_train)

y_pred2 = clf.predict(X_test_trf)
y_pred2

accuracy_score(Y_test,y_pred2)

trf_test = trf.fit_transform(X)

np.mean(cross_val_score(DecisionTreeClassifier(),X,Y,cv=5,scoring="accuracy"))

def discretized(bins, strategy, X_train, X_test, Y_train, Y_test):
    # Create discretizers
    kb_age = KBinsDiscretizer(n_bins=bins, encode="ordinal", strategy=strategy)
    kb_fire = KBinsDiscretizer(n_bins=bins, encode="ordinal", strategy=strategy)

    # ColumnTransformer
    trf = ColumnTransformer([
        ("age_bin", kb_age, [0]),
        ("fire_bin", kb_fire, [1])
    ])

    # Transform training and testing sets
    X_train_trf = trf.fit_transform(X_train)
    X_test_trf = trf.transform(X_test)

    # Train classifier
    clf = DecisionTreeClassifier()
    clf.fit(X_train_trf, Y_train)

    # Predict
    y_pred2 = clf.predict(X_test_trf)
    test_acc = accuracy_score(Y_test, y_pred2)
    print("Test Accuracy:", test_acc)

    # Cross-validation on full transformed data
    X_trf_full = trf.fit_transform(np.vstack((X_train, X_test)))
    Y_full = np.hstack((Y_train, Y_test))
    cv_acc = np.mean(cross_val_score(DecisionTreeClassifier(), X_trf_full, Y_full, cv=5, scoring="accuracy"))
    print("Cross-validation Accuracy:", cv_acc)


    plt.figure(figsize=(14,4))
    plt.subplot(121)
    plt.hist(X["age"])
    plt.title("Age Before Discretization")

    plt.subplot(122)
    plt.hist( X_trf_full[:,0],color = "red")
    plt.title("Age after Discretization")


    plt.figure(figsize=(14,4))
    plt.subplot(121)
    plt.hist(X["fare"])
    plt.title("fare Before Discretization")

    plt.subplot(122)
    plt.hist( X_trf_full[:,1],color = "g")
    plt.title("fare after Discretization")

    return clf, test_acc, cv_acc

clf, test_acc, cv_acc = discretized(10, "quantile", X_train, X_test, Y_train, Y_test)

def discretized(bins, strategy, X_train, X_test, Y_train, Y_test):
    # Create discretizers
    kb_age = KBinsDiscretizer(n_bins=bins, encode="ordinal", strategy=strategy)
    kb_fire = KBinsDiscretizer(n_bins=bins, encode="ordinal", strategy=strategy)

    # ColumnTransformer
    trf = ColumnTransformer([
        ("age_bin", kb_age, [0]),
        ("fire_bin", kb_fire, [1])
    ])

    # Transform training and testing sets
    X_train_trf = trf.fit_transform(X_train)
    X_test_trf = trf.transform(X_test)

    # Train classifier
    clf = DecisionTreeClassifier()
    clf.fit(X_train_trf, Y_train)

    # Predict
    y_pred2 = clf.predict(X_test_trf)
    test_acc = accuracy_score(Y_test, y_pred2)
    print("Test Accuracy:", test_acc)

    # Cross-validation on full transformed data
    X_trf_full = trf.fit_transform(np.vstack((X_train, X_test)))
    Y_full = np.hstack((Y_train, Y_test))
    cv_acc = np.mean(cross_val_score(DecisionTreeClassifier(), X_trf_full, Y_full, cv=5, scoring="accuracy"))
    print("Cross-validation Accuracy:", cv_acc)


    plt.figure(figsize=(14,4))
    plt.subplot(121)
    plt.hist(X["age"])
    plt.title("Age Before Discretization")

    plt.subplot(122)
    plt.hist( X_trf_full[:,0],color = "red")
    plt.title("Age after Discretization")


    plt.figure(figsize=(14,4))
    plt.subplot(121)
    plt.hist(X["fare"])
    plt.title("fare Before Discretization")

    plt.subplot(122)
    plt.hist( X_trf_full[:,1],color = "g")
    plt.title("fare after Discretization")

    return clf, test_acc, cv_acc

clf, test_acc, cv_acc = discretized(5, "uniform", X_train, X_test, Y_train, Y_test)

clf, test_acc, cv_acc = discretized(10, "kmeans", X_train, X_test, Y_train, Y_test)