# -*- coding: utf-8 -*-
"""Houseing using Linear Regression .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prg-mF0SbQIuTxsNuzigQsA4n_vxWDj7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

df1 = pd.read_csv("/content/Housing (1).csv")
df1.head()

df2 = df1.iloc[:,0:2]
df2.head()

df2.sample(5)

df2.describe()

df2.isnull().sum()

# visualization

sns.scatterplot(x=df2["area"],y=df2["price"])
plt.title("Area vs Price")
plt.show()

X = df2.iloc[:,1]
y = df2.iloc[:,0]

X.head()

y.head()

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

X_train.head()

X_test

y_test

X_train = X_train.values.reshape(-1,1)

model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test.values.reshape(-1,1))

y_pred

model.predict([[5000]])

mse = mean_squared_error(y_test,y_pred)

r2 = r2_score(y_test,y_pred)

print("MSE:",mse)

print("R2 Score:",r2)

plt.scatter(X_test,y_test)

plt.plot(X_test,y_pred,color="red")

plt.xlabel("Area")

plt.ylabel("Price")

plt.title("Linear Regression Model")

plt.show()

import pickle

pickle.dump(model,open("model.pkl","wb"))

model = pickle.load(open("model.pkl","rb"))

area = float(input("Enter house area: "))

prediction = model.predict([[area]])

print("Predicted price:",prediction)

print("Slope:",model.coef_)
print("Intercept:",model.intercept_)

"""SEcond method"""

class LinearRegression:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train,y_train):

        num = 0
        den = 0

        for i in range(X_train.shape[0]):

            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean()))*((X_train[i] - X_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,X_test):
        print(X_test)
        return self.m * X_test + self.b

df2 = df1.iloc[:,0:2]
df2.head()

X = df1.iloc[:,1].values
y = df1.iloc[:,0].values

X

y

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

X_train.shape

lr = LinearRegression()

lr.fit(X_train,y_train)

X_test

y_test

print(lr.predict(X_test[1]))

X_test

y_test