# -*- coding: utf-8 -*-
"""Placement.csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHYV_HqvinXsYEcHCawEXkSgMvk1FADK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.metrics import mean_absolute_error

df = pd.read_csv("/content/placement.csv")
df.head()

df.isnull().sum()

df.duplicated().sum()

plt.scatter(df["cgpa"],df["package"])
plt.xlabel("cgpa")
plt.ylabel("package")
plt.grid(True)
plt.show()

sns.regplot(x="cgpa", y="package", data=df,color = "r")

plt.show()

x = df.iloc[:,0:1]
y = df.iloc[:,-1]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

x_train.shape

x_test.shape

lr = LinearRegression()

lr.fit(x_train,y_train)

plt.scatter(df["cgpa"],df["package"])
plt.plot(x_train,lr.predict(x_train),color = "r")
plt.xlabel("cgpa")
plt.ylabel("package")
plt.show()

y_pred = lr.predict(x_test)
y_pred

np.array(y_test)

y_test.values

print("mean_absolute_error","=",mean_absolute_error(y_test,y_pred))

print("mean_squared_error","=",mean_squared_error(y_test,y_pred))

print("RMSE","=",np.sqrt(mean_squared_error(y_test,y_pred)))

r2 = r2_score(y_test,y_pred)
print("r2_score","=",r2)

adjusted_r2 = 1 - ((1 - r2) * (40 - 1) / (40 - 1 - 1))
print("Adjusted R2 Score =", adjusted_r2)

new_df = df.copy()
new_df["random_feature"] = np.random.random(200)
new_df = new_df[["cgpa","random_feature","package"]]
new_df.head()

plt.scatter(new_df["random_feature"],new_df["package"])
plt.xlabel("random_feature")
plt.ylabel("package")
plt.show()

X = new_df.iloc[:,0:2]
Y = new_df.iloc[:,-1]

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=3)

X_train.shape,X_test.shape

X_train

lr1 = LinearRegression()

lr1.fit(X_train,Y_train)

plt.scatter(new_df["random_feature"],new_df["package"])
plt.plot(X_train,lr1.predict(X_train),color = "r")
plt.xlabel("random_feature")
plt.ylabel("package")
plt.show()

y_pred1 = lr1.predict(X_test)
y_pred1

np.array(Y_test)

print("mean_absolute_error","=",mean_absolute_error(Y_test,y_pred1))

print("mean_squared_error","=",mean_squared_error(Y_test,y_pred1))

print("RMSE","=",np.sqrt(mean_squared_error(Y_test,y_pred1)))

R2 = r2_score(Y_test,y_pred1)
print("r2_score","=",R2)

X_test.shape

#adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - p - 1))  X_test.shape where n = X_test.shape[0] and p =  X_test.shape[1]

adjusted_R2 = 1 - ((1 - R2) * (40 - 1) / (40 - 2 - 1))
print("Adjusted R2 Score =", adjusted_R2)