# -*- coding: utf-8 -*-
"""powerTransformer using ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4UtNDD8zfAnX1JU5Gk7YWPlfoVEKQR_
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import FunctionTransformer,PowerTransformer

df2 = pd.read_csv("/content/concrete_data.csv")

df2.head()

df2.shape

df2.isnull().sum()

df2.duplicated().sum()

df2[df2.duplicated()]

df2 = df2.drop_duplicates()

int(df2.duplicated().sum())

df2.shape

df2.describe()

X = df2.drop(columns="Strength")
Y = df2.iloc[:,-1]

X.shape

Y.shape

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42)

X_train.shape

X_train.head()

X_test.shape

X_train.columns

for col in X_train.columns:
    plt.figure(figsize=(14,4))

    plt.subplot(121)
    sns.histplot(X_train[col], kde=True)
    plt.title(f"{col} - Distribution")

    plt.subplot(122)
    stats.probplot(X_train[col], dist="norm", plot=plt)
    plt.title(f"{col} - Q-Q Plot")

    plt.show()

lr  = LinearRegression()
DT = DecisionTreeRegressor()

lr.fit(X_train,Y_train)
DT.fit(X_train,Y_train)

y_pred = lr.predict(X_test)
y_pred1 = DT.predict(X_test)

print(f"calculated of Linear_Regression :----")
print("MAE =", mean_absolute_error(Y_test, y_pred))
print("MSE =", mean_squared_error(Y_test, y_pred))
print("RMSE =", np.sqrt(mean_squared_error(Y_test, y_pred)))
print("R2 =", r2_score(Y_test, y_pred))
print("   ")
print(f"calculated of DecisionTreeRegressor :----")
print("MAE =", mean_absolute_error(Y_test, y_pred1))
print("MSE =", mean_squared_error(Y_test, y_pred1))
print("RMSE =", np.sqrt(mean_squared_error(Y_test, y_pred1)))
print("R2 =", r2_score(Y_test, y_pred1))

scores = cross_val_score(lr, X, Y, cv=10, scoring='r2')

print("Cross-val scores: LinearRegression", scores)
print("Mean accuracy:LinearRegression", scores.mean())
print("  ")
scores = cross_val_score(DT, X, Y, cv=10, scoring='r2')

print("Cross-val scores: DT", scores)
print("Mean accuracy:DT", scores.mean())

pt =  PowerTransformer(method = "box-cox")

X_train_transformed = pt.fit_transform(X_train+0.000001)
X_test_transformed = pt.fit_transform(X_test+0.000001)

pd.DataFrame({"cols":X_train.columns,"box-cox_lembda":pt.lambdas_})

lr.fit(X_train_transformed,Y_train)
DT.fit(X_train_transformed,Y_train)

y_pred = lr.predict(X_test_transformed)
y_pred1 = DT.predict(X_test_transformed)

print(f"calculated of Linear_Regression :----")
print("MAE =", mean_absolute_error(Y_test, y_pred))
print("MSE =", mean_squared_error(Y_test, y_pred))
print("RMSE =", np.sqrt(mean_squared_error(Y_test, y_pred)))
print("R2 =", r2_score(Y_test, y_pred))
print("   ")
print(f"calculated of DecisionTreeRegressor :----")
print("MAE =", mean_absolute_error(Y_test, y_pred1))
print("MSE =", mean_squared_error(Y_test, y_pred1))
print("RMSE =", np.sqrt(mean_squared_error(Y_test, y_pred1)))
print("R2 =", r2_score(Y_test, y_pred1))

X_transformed1 = pt.fit_transform(X+0.0001)
scores = cross_val_score(lr, X_transformed1, Y, cv=10, scoring='r2')

print("Cross-val scores: LinearRegression", scores)
print("Mean accuracy:LinearRegression", scores.mean())
print("  ")
scores = cross_val_score(DT, X_transformed1, Y, cv=10, scoring='r2')

print("Cross-val scores: DT", scores)
print("Mean accuracy:DT", scores.mean())

X_train_transformed1 = pd.DataFrame(X_train_transformed,columns=X_train.columns)

X_train_transformed1.head()

for cols in X_train_transformed1.columns:
  print(cols)

for cols in X_train.columns:
  print(cols)

for col in X_train_transformed1.columns:
  plt.figure(figsize=(14,4))
  plt.subplot(121)
  sns.histplot(X_train[col], kde=True)
  plt.title(col)

  plt.subplot(122)
  sns.histplot(X_train_transformed1[col], kde=True)
  plt.title(col)

  plt.show()

# apply YO-johnson method(defult method)

pt1 = PowerTransformer()

X_train_transformed2 = pt1.fit_transform(X_train)
X_test_transformed2 = pt1.fit_transform(X_test)

pd.DataFrame({"cols":X_train.columns,"yo-johnson_lembda":pt1.lambdas_})

lr.fit(X_train_transformed2,Y_train)
DT.fit(X_train_transformed2,Y_train)

y_pred = lr.predict(X_test_transformed2)
y_pred1 = DT.predict(X_test_transformed2)

print(f"calculated of Linear_Regression :----")
print("MAE =", mean_absolute_error(Y_test, y_pred))
print("MSE =", mean_squared_error(Y_test, y_pred))
print("RMSE =", np.sqrt(mean_squared_error(Y_test, y_pred)))
print("R2 =", r2_score(Y_test, y_pred))
print("   ")
print(f"calculated of DecisionTreeRegressor :----")
print("MAE =", mean_absolute_error(Y_test, y_pred1))
print("MSE =", mean_squared_error(Y_test, y_pred1))
print("RMSE =", np.sqrt(mean_squared_error(Y_test, y_pred1)))
print("R2 =", r2_score(Y_test, y_pred1))

X_transformed2 = pt1.fit_transform(X)
scores = cross_val_score(lr, X_transformed2, Y, cv=10, scoring='r2')

print("Cross-val scores: LinearRegression", scores)
print("Mean accuracy:LinearRegression", scores.mean())
print("  ")
scores = cross_val_score(DT, X_transformed2, Y, cv=10, scoring='r2')

print("Cross-val scores: DT", scores)
print("Mean accuracy:DT", scores.mean())

X_train_transformed3 = pd.DataFrame(X_train_transformed2,columns=X_train.columns)

X_train_transformed3.head()

for col in X_train_transformed3.columns:
  plt.figure(figsize=(14,4))
  plt.subplot(121)
  sns.histplot(X_train[col], kde=True)
  plt.title(col)

  plt.subplot(122)
  sns.histplot(X_train_transformed3[col], kde=True)
  plt.title(col)

  plt.show()

pd.DataFrame({"cols":X_train.columns,"box-cox_lambda":pt.lambdas_,"yo-johnson_lambda":pt1.lambdas_})