# -*- coding: utf-8 -*-
"""Principle Component Analysis (PCA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMQC6W2umSiW7R0Kzpy6x0MVVneIy5nE
"""

import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.preprocessing import StandardScaler

np.random.seed(23) # Normally, random functions generate different numbers each time the program runs.
                    #By setting a seed value, the random sequence becomes reproducible.

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

mu_vec1 = np.array([0,0,0])
mu_vec1

cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
cov_mat1

"""np.random.multivariate_normal() is a function in NumPy used to generate random samples from a multivariate normal (Gaussian) distribution.

A multivariate normal distribution means a normal distribution with multiple variables that may be correlated with each other.

mean
A list or array representing the mean values of each variable.

cov
The covariance matrix, which describes the variance of each variable and the relationship between variables.

size
The number of random samples to generate.

Uni-variate → one variable (example: only height)

Multi-variate → multiple variables (example: height and weight)

Multivariate distribution also considers the relationship (covariance) between variables.
"""

class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

class1_sample

type(class1_sample)

class1_sample.ndim

class1_sample.shape

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])

df.head()

df['target'] = 1

df.head()

mu_vec2 = np.array([1,1,1])
mu_vec2

cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
cov_mat2

class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)
class2_sample

type(class1_sample)

class1_sample.ndim

class1_sample.shape

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1.head()

df1['target'] = 0
df1.head()

df2 = pd.concat([df, df1], ignore_index=True)
df2.head()

df2.shape

df2.ndim

df2.sample(10)

df2.info()

df2.describe()

fig = px.scatter_3d(df2, x=df2['feature1'], y=df2['feature2'], z=df2['feature3'],
              color=df2['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

# Step 1 - Apply standard scaling

scaler = StandardScaler()

df2.iloc[:,0:3] = scaler.fit_transform(df2.iloc[:,0:3])

# Step 2 - Find Covariance Matrix

covariance_matrix = np.cov([df2.iloc[:,0],df2.iloc[:,1],df2.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

# Step 3 - Finding eigen_values and eigen_vectors
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

eigen_values

eigen_vectors

# Commented out IPython magic to ensure Python compatibility.
# %pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):

    def __init__(self, xs, ys, zs, *args, **kwargs):
        super().__init__((0,0),(0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def do_3d_projection(self, renderer=None):
        xs3d, ys3d, zs3d = self._verts3d
        return min(zs3d)

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.get_proj())
        self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))
        super().draw(renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df2['feature1'], df2['feature2'], df2['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df2['feature1'].mean()], [df2['feature2'].mean()], [df2['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df2['feature1'].mean(), v[0]], [df2['feature2'].mean(), v[1]], [df2['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

plt.show()

pc = eigen_vectors[0:2]
pc

transformed_df = np.dot(df2.iloc[:,0:3],pc.T)

transformed_df

df2.shape

transformed_df.shape

# 40,3 - 3,2

new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])

new_df.sample(5)

new_df['target'] = df2['target'].values
new_df.sample(5)

new_df['target'] = new_df['target'].astype('str')

fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()