# -*- coding: utf-8 -*-
"""RobustScaler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xndt1AxOinfpQ-45CMst1BVbOhqNtTFa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

df = pd.read_csv("/content/Social_Network_Ads (1).csv")

df.head()

round(df.describe(),1)

df = df.iloc[:, 2:]

df.head()

X_train,X_test,y_train,y_test = train_test_split(df.drop("Purchased",axis =1),
                                                 df["Purchased"],test_size=0.3,random_state=0)

X_train.shape,X_test.shape

X_train.head()

X_test.head()

Scaler = StandardScaler()
Scaler.fit(X_train)

X_train_scaled = Scaler.transform(X_train)
X_test_scaled  = Scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled,columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns = X_test.columns)

X_train_scaled.head()

X_test_scaled.head()

round(X_train_scaled.describe(),1)

round(X_test_scaled.describe(),1)

# Effect of Scaling

fig,(ax1,ax2) = plt.subplots(ncols = 2,figsize = (12,5))
ax1.scatter(X_train["Age"],X_train["EstimatedSalary"],color = "red")
plt.xlabel("Age")
plt.ylabel("Salary")
ax1.set_title("before Scalling")
ax2.scatter(X_train_scaled["Age"],X_train_scaled["EstimatedSalary"],color = "g")
plt.xlabel("Age")
plt.ylabel("Salary")
ax2.set_title("after Scalling")
plt.show()

fig,(ax1,ax2) = plt.subplots(ncols = 2,figsize = (12,5))
ax1.scatter(X_test["Age"],X_test["EstimatedSalary"],color = "red")
plt.xlabel("Age")
plt.ylabel("Salary")
ax1.set_title("before Scalling")
ax2.scatter(X_test_scaled["Age"],X_test_scaled["EstimatedSalary"],color = "g")
plt.xlabel("Age")
plt.ylabel("Salary")
ax2.set_title("after Scalling")
plt.show()

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12,5))

# Before Scaling
ax1.set_title("Before Scaling")
sns.kdeplot(X_train["Age"], ax=ax1, label="Age")
sns.kdeplot(X_train["EstimatedSalary"], ax=ax1, label="Estimated Salary")
ax1.legend()

# After Scaling
ax2.set_title("After Scaling")
sns.kdeplot(X_train_scaled["Age"], ax=ax2, label="Age (Scaled)")
sns.kdeplot(X_train_scaled["EstimatedSalary"], ax=ax2, label="Estimated Salary (Scaled)")
ax2.legend()

plt.show()

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12,5))

# Before Scaling
ax1.set_title("Before Scaling")
sns.kdeplot(X_test["Age"], ax=ax1, label="Age")
sns.kdeplot(X_test["EstimatedSalary"], ax=ax1, label="Estimated Salary")
ax1.legend()

# After Scaling
ax2.set_title("After Scaling")
sns.kdeplot(X_test_scaled["Age"], ax=ax2, label="Age (Scaled)")
sns.kdeplot(X_test_scaled["EstimatedSalary"], ax=ax2, label="Estimated Salary (Scaled)")
ax2.legend()

plt.show()

# comprision of distribution
fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12,5))
# Before Scaling
ax1.set_title("Before Scaling")
sns.kdeplot(X_train["Age"],ax = ax1,color="r")
# After Scaling
ax2.set_title("After Scaling")
sns.kdeplot(X_train_scaled["Age"],ax = ax2,color="g")
plt.show()

# comprision of distribution
fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12,5))
# Before Scaling
ax1.set_title("Before Scaling")
sns.kdeplot(X_train["EstimatedSalary"],ax = ax1,color="r")
# After Scaling
ax2.set_title("After Scaling")
sns.kdeplot(X_train_scaled["EstimatedSalary"],ax = ax2,color="g")
plt.show()

# Logistic_model

log = LogisticRegression()
log_scaled = LogisticRegression()

log.fit(X_train,y_train)
log_scaled.fit(X_train_scaled,y_train)

y_pred = log.predict(X_test)
Y_pred_scaled = log_scaled.predict(X_test_scaled)

print("Accuracy_score before scaling",accuracy_score(y_test, y_pred))
print("Accuracy_score After Scaling",accuracy_score(y_test, Y_pred_scaled))

# DECIGiON TREE

dt = DecisionTreeClassifier()
dt_Scaled = DecisionTreeClassifier()

dt.fit(X_train,y_train)
dt_Scaled.fit(X_train_scaled,y_train)

y_preddt = dt.predict(X_test)
y_preddt_scaled = dt_Scaled.predict(X_test_scaled)

print("Actual accuracy score before scaling",accuracy_score(y_test,y_preddt))
print("scaled accuracy score after scaling ",accuracy_score(y_test,y_preddt_scaled))

model = RandomForestClassifier(n_estimators=100, random_state=42)
model_scaled = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train,y_train)
model_scaled.fit(X_train_scaled,y_train)

y_predRF = model.predict(X_test)
y_predRF_scaled = model_scaled.predict(X_test_scaled )

print("Actual Accoracy before scaling",accuracy_score(y_test,y_predRF))
print("scaled Accuracy after scaling ",accuracy_score(y_test,y_predRF_scaled))

knnmodel = KNeighborsClassifier(n_neighbors=5)
knnmodel_scaled = KNeighborsClassifier(n_neighbors=5)

knnmodel.fit(X_train,y_train)
knnmodel_scaled.fit(X_train_scaled,y_train)

y_predknn = knnmodel.predict(X_test)
y_predknn_scaled = knnmodel_scaled.predict(X_test_scaled)

print("Actual Accoracy before scaling",accuracy_score(y_test,y_predknn))
print("scaled Accuracy after scaling ",accuracy_score(y_test,y_predknn_scaled))

SVM1 = SVC()
SVM1_scaled = SVC()

SVM1.fit(X_train,y_train)
SVM1_scaled.fit(X_train_scaled,y_train)

y_predSVM = SVM1.predict(X_test)
y_predSVM_scaled = SVM1_scaled.predict(X_test_scaled)

print("Actual Accoracy before scaling",accuracy_score(y_test,y_predSVM))
print("scaled Accuracy after scaling ",accuracy_score(y_test,y_predSVM_scaled))

# With Outlier

df = pd.concat(
    [
        df,
        pd.DataFrame({
            "Age": [5, 80, 90],
            "EstimatedSalary": [1000, 30000, 70000],
            "Purchased": [0, 1, 1]
        })
    ],
    ignore_index=True
)

df.head()

plt.scatter(df["Age"],df["EstimatedSalary"])

X_train,X_test,y_train,y_test = train_test_split(df.drop("Purchased",axis =1),
                                                 df["Purchased"],test_size=0.3,random_state=0)

X_train.shape,X_test.shape

Scaler = StandardScaler()
Scaler.fit(X_train)

X_train_scaled = Scaler.transform(X_train)
X_test_scaled  = Scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled,columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns = X_test.columns)

# Effect of Scaling

fig,(ax1,ax2) = plt.subplots(ncols = 2,figsize = (12,5))
ax1.scatter(X_train["Age"],X_train["EstimatedSalary"],color = "red")
plt.xlabel("Age")
plt.ylabel("Salary")
ax1.set_title("before Scalling")
ax2.scatter(X_train_scaled["Age"],X_train_scaled["EstimatedSalary"],color = "g")
plt.xlabel("Age")
plt.ylabel("Salary")
ax2.set_title("after Scalling")
plt.show()

fig,(ax1,ax2) = plt.subplots(ncols = 2,figsize = (12,5))
ax1.scatter(X_test["Age"],X_test["EstimatedSalary"],color = "red")
plt.xlabel("Age")
plt.ylabel("Salary")
ax1.set_title("before Scalling")
ax2.scatter(X_test_scaled["Age"],X_test_scaled["EstimatedSalary"],color = "g")
plt.xlabel("Age")
plt.ylabel("Salary")
ax2.set_title("after Scalling")
plt.show()

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12,5))

# Before Scaling
ax1.set_title("Before Scaling")
sns.kdeplot(X_train["Age"], ax=ax1, label="Age")
sns.kdeplot(X_train["EstimatedSalary"], ax=ax1, label="Estimated Salary")
ax1.legend()

# After Scaling
ax2.set_title("After Scaling")
sns.kdeplot(X_train_scaled["Age"], ax=ax2, label="Age (Scaled)")
sns.kdeplot(X_train_scaled["EstimatedSalary"], ax=ax2, label="Estimated Salary (Scaled)")
ax2.legend()

plt.show()

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12,5))

# Before Scaling
ax1.set_title("Before Scaling")
sns.kdeplot(X_test["Age"], ax=ax1, label="Age")
sns.kdeplot(X_test["EstimatedSalary"], ax=ax1, label="Estimated Salary")
ax1.legend()

# After Scaling
ax2.set_title("After Scaling")
sns.kdeplot(X_test_scaled["Age"], ax=ax2, label="Age (Scaled)")
sns.kdeplot(X_test_scaled["EstimatedSalary"], ax=ax2, label="Estimated Salary (Scaled)")
ax2.legend()

plt.show()

# Logistic_model

log = LogisticRegression()
log_scaled = LogisticRegression()

log.fit(X_train,y_train)
log_scaled.fit(X_train_scaled,y_train)

y_pred = log.predict(X_test)
Y_pred_scaled = log_scaled.predict(X_test_scaled)

print("Accuracy_score before scaling",accuracy_score(y_test, y_pred))
print("Accuracy_score After Scaling",accuracy_score(y_test, Y_pred_scaled))

dt = DecisionTreeClassifier()
dt_Scaled = DecisionTreeClassifier()

dt.fit(X_train,y_train)
dt_Scaled.fit(X_train_scaled,y_train)

y_preddt = dt.predict(X_test)
y_preddt_scaled = dt_Scaled.predict(X_test_scaled)

print("Actual accuracy score before scaling",accuracy_score(y_test,y_preddt))
print("scaled accuracy score after scaling ",accuracy_score(y_test,y_preddt_scaled))

model = RandomForestClassifier(n_estimators=100, random_state=42)
model_scaled = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train,y_train)
model_scaled.fit(X_train_scaled,y_train)

y_predRF = model.predict(X_test)
y_predRF_scaled = model_scaled.predict(X_test_scaled )

print("Actual accuracy score before scaling",accuracy_score(y_test,y_predRF))
print("scaled accuracy score after scaling ",accuracy_score(y_test,y_predRF_scaled))

knnmodel = KNeighborsClassifier(n_neighbors=5)
knnmodel_scaled = KNeighborsClassifier(n_neighbors=5)

knnmodel.fit(X_train,y_train)
knnmodel_scaled.fit(X_train_scaled,y_train)

y_predknn = knnmodel.predict(X_test)
y_predknn_scaled = knnmodel_scaled.predict(X_test_scaled)

print("Actual Accoracy before scaling",accuracy_score(y_test,y_predknn))
print("scaled Accuracy after scaling ",accuracy_score(y_test,y_predknn_scaled))

SVM1 = SVC()
SVM1_scaled = SVC()

SVM1.fit(X_train,y_train)
SVM1_scaled.fit(X_train_scaled,y_train)

y_predSVM = SVM1.predict(X_test)
y_predSVM_scaled = SVM1_scaled.predict(X_test_scaled)

print("Actual Accoracy before scaling",accuracy_score(y_test,y_predSVM))
print("scaled Accuracy after scaling ",accuracy_score(y_test,y_predSVM_scaled))